# Cloudflare Pages configuration for Web Creator
name = "web-creator"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-26"

# Environment variables for production build
[env.production.vars]
NODE_ENV = "production"
VITE_APP_NAME = "Web Creator"
VITE_APP_VERSION = "1.0.0"

# Environment variables for preview builds
[env.preview.vars]
NODE_ENV = "development"
VITE_APP_NAME = "Web Creator Preview"
