# Cloudflare Pages configuration for Web Creator
# Required by Pages config validation:
# - name: your Pages project name
# - pages_build_output_dir: directory where the static build is output

name = "web-creator"
pages_build_output_dir = "dist"
